# Generated by Django 5.1.2 on 2024-10-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='fax_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registration Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Code'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='VAT Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
