# Generated by Django 5.1.2 on 2024-10-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_supplier_fax_number_supplier_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Invoice File'),
        ),
    ]
