# Generated by Django 5.1.2 on 2024-10-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveditem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='receiveditem',
            name='vendor_code',
            field=models.CharField(default=0, max_length=100, verbose_name='Vendor Code'),
            preserve_default=False,
        ),
    ]
