# Generated by Django 5.1.2 on 2024-10-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_supplier_bank_supplier_iban_supplier_swift'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Shipping Fee'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_address',
            field=models.TextField(blank=True, null=True, verbose_name='Bank Address'),
        ),
    ]
