# Generated by Django 5.1.2 on 2024-10-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_invoice_discount_invoice_shipping_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_fee',
        ),
        migrations.AddField(
            model_name='invoice',
            name='fee_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fee After Discount'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fee_before_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fee Before Discount'),
        ),
    ]
